### ISSUE TITLE
Is this compatible with bootstrap 3.3.5?

### ISSUE THREAD

**Issue by anjos** [dbtek/chosen-bootstrap#4]
If so, would you mind releasing a package fixing the bower dependence to `~3.3.5` instead? Currently, it conflicts with the latest version of bootstrap available to bower.

**Comment by dbtek** [comment]
It should be. Checking.

**Comment by dbtek** [comment]
It's now supported with [1.1.0 release](https://github.com/dbtek/chosen-bootstrap/releases/tag/1.1.0).

**Comment by anjos** [comment]
Awesome, thanks!

**Comment by dbtek** [comment]
You're welcome, glad to help.
